version: '3'

services:
  #docker compose up
  django:
    image: ${DOCKER_DJANGO_IMAGE:-darlon/django:3}
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./:/src
    env_file:
      - .env
    networks:
      - django-net
    #caminho para manage.py
    working_dir: /src/
    #comando para executar django
    command: python3 manage.py runserver 0.0.0.0:8000

  #docker compose up migrate
  migrate:
    image: ${DOCKER_DJANGO_IMAGE:-darlon/django:3}
    depends_on:
      - postgres
    profiles: [ 'init' ]
    volumes:
      - ./:/src
    env_file:
      - .env
    networks:
      - django-net
    #caminho para manage.py
    working_dir: /src/
    #comando para makemigrations e migrate
    command: /bin/bash -c "python3 manage.py makemigrations && python3 manage.py migrate"

  #docker compose up populate
  populate:
    image: ${DOCKER_DJANGO_IMAGE:-darlon/django:3}
    profiles: [ 'init' ]
    depends_on:
      - migrate
    volumes:
      - ./:/src
    env_file:
      - .env
    networks:
      - django-net
    #caminho para manage.py
    working_dir: /src/
    #comando para executar o script 
    command: /bin/bash -c "python3 manage.py runscript populate"

  #docker compose run bash
  #-->> RUN <<--  ^^^  
  bash:
    image: ${DOCKER_DJANGO_IMAGE:-darlon/django:3}
    profiles: [ 'bash' ]
    stdin_open: true
    tty: true
    user: "${UID}:${GID}"
    volumes:
      - ./:/src
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    env_file:
      - .env
    networks:
      - django-net
    working_dir: /src/
    command: /bin/bash

  #docker compose up postgres
  postgres:
    image: ${POSTGRES_IMAGE:-postgres:16.0-bullseye}
    env_file:
      - .env
    user: "${UID}:${GID}"
    ports:
      - "15432:5432"
    volumes:
      - ./db/:/var/lib/postgresql/data/
    networks:
      - django-net

  # https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html
  # docker compose up pgadmin
  pgadmin:
    image: ${PGADMIN_IMAGE:-dpage/pgadmin4:7.7}
    profiles: [ 'monitor' ]
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "16543:80"
    networks:
      - django-net

networks:
  django-net:
    driver: bridge
